# Banco de Dados H2 Em Memória (Demonstração Local e Teste de Criptografia)
spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desabilita logs extensivos para facilitar a visualização no terminal
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# APIs do Ecos (Mesmas de DEV)
llam.ecos.urls.person.get-all=http://localhost:8081/person
llam.ecos.urls.person.create=http://localhost:8081/person
llam.ecos.urls.person.get-by-id=http://localhost:8081/person/{personId}
llam.ecos.urls.person.update=http://localhost:8081/person/{personId}
llam.ecos.urls.person.delete=http://localhost:8081/person/{personId}
llam.ecos.urls.classification.get-classes=http://localhost:8082/class
llam.ecos.urls.transaction.create-transaction=http://localhost:8085/transaction
